### PR TITLE
[WIP] Improve documentation

### PR DESCRIPTION
**Pull request by Birdie0**
do not merge till further notice

### CODE REVIEW

**Comment by Doc1337** [comment]
mee6 still exists? i though everyone use dyno or their own bots

**Comment by SilBoydens** [comment]
Ready or wait?

**Comment by Birdie0** [comment]
still wait

* [ ] fill pages with text
* [ ] update screenshots
* [ ] fix markdown
* [ ] make sure it looks good

**Comment by Birdie0** [comment]
i'm done

**Pull request merged**
